" Dependencies:
" Plug
" nerdtree 
" vim-airline
" vim-airline-themes
" vim-gruvbox theme
" powerline fonts

source /usr/share/vim/vim82/defaults.vim

" Plugins ---------- {{{
call plug#begin()
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
call plug#end()
" }}}

" Basic settings ---------- {{{
set clipboard=unnamedplus
set tabstop=4
set shiftwidth=4
set number
set termguicolors
set spelllang=en
" }}}

" Mappings ---------- {{{
let mapleader = "\<bs>"

" leave insert mode with 'jk'
inoremap jk <esc>

" move to end/start
nnoremap J G
nnoremap K gg
vnoremap J G
vnoremap K gg

"" switch word's case
nnoremap <leader>u viw~e

"" quote word/selection
nnoremap <leader>" mcviw<esc>a"<esc>bi"<esc>`cl
nnoremap <leader>' mcviw<esc>a'<esc>bi'<esc>`cl
vnoremap <leader>" mc<esc>`>a"<esc>`<i"<esc>`cl
vnoremap <leader>' mc<esc>`>a'<esc>`<i'<esc>`cl

"" move current line up/down
nnoremap <C-j> ddp
nnoremap <C-k> ddkP

"" split shortcuts
noremap <C-Down> <C-W>j
noremap <C-Up> <C-W>k
noremap <C-Left> <C-W>h
noremap <C-Right> <C-W>l
noremap <C-S-Up> :res +5<CR>
noremap <C-S-Down> :res -5<CR>
noremap <C-S-Right> :vertical resize +5<CR>
noremap <C-S-Left> :vertical resize -5<CR>

" pull up file browser
noremap <C-n> :NERDTree .<CR>

" theme control
noremap <F5> :set background=light<CR>
noremap <F6> :set background=dark<CR>

" Toggle [relative] number
noremap <leader>N :set number!<CR>
noremap <leader>n :set relativenumber!<CR>

" Toggle spell
nnoremap <leader>S :set spell!<CR>

" Toggle search highlighting
nnoremap <leader>h :set hlsearch!<CR>

" Quick vimrc editing
nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>
" }}}

" Filetype-specific settings ---------- {{{
augroup vim_filetype
	autocmd!
	autocmd FileType vim setlocal foldmethod=marker
augroup END

func Eatchar(pat)
	let c = nr2char(getchar(0))
	return (c =~ a:pat) ? '' : c
endfunc

augroup java_filetype
	autocmd!
	autocmd FileType java iabbrev <buffer> sop System.out.print();<left><left><C-R>=Eatchar('\s')<CR>
	autocmd FileType java iabbrev <buffer> sopl System.out.println();<left><left><C-R>=Eatchar('\s')<CR>
	autocmd FileType java iabbrev <buffer> mmain public static class Main {<CR>public static void main(String[] args) {<CR>}<CR>}<esc>kO
augroup END

augroup c_filetype
	autocmd!
	autocmd FileType c iabbrev <buffer> if if ()<left><C-R>=Eatchar('\s')<CR>
augroup END

augroup tex_filetype
	autocmd!
	autocmd BufWritePost *.tex :!cd $(dirname %) && xelatex $(basename %)
augroup END
" }}}

" Theme ---------- {{{
" Airline
let g:airline_theme='zenburn'
let g:airline_powerline_fonts = 1

" Color scheme
set background=light
let g:gruvbox_contrast_dark='light'
let g:gruvbox_contrast_light='hard'
colorscheme gruvbox
" }}}
